# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

opnmfR_opnmfRcpp <- function(X, W0, tol, maxiter, eps, memsave) {
  .Call(`_opnmfR_opnmfR_opnmfRcpp`, X, W0, tol, maxiter, eps, memsave)
}

